DROP TABLE IF EXISTS Collaudo; 
DROP TABLE IF EXISTS rapporto_mobile_collaudo;
CREATE TABLE `rapporto_mobile_collaudo` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Id_rapporto` SMALLINT(6) NOT NULL,
	`Anno` SMALLINT(6) NOT NULL,
	`Id_cliente` INT(11) NOT NULL,
	`Id_impianto` INT(11) NULL DEFAULT NULL,
	`Indirizzo` VARCHAR(255) NOT NULL,
	`Telefono` VARCHAR(20) NULL DEFAULT NULL,
	`Fax` VARCHAR(20) NULL DEFAULT NULL,
	`Partita_iva_cod_fisc` VARCHAR(20) NULL DEFAULT NULL,
	`Richiedente_intervento` VARCHAR(30) NULL DEFAULT NULL,
	`Email` VARCHAR(35) NULL DEFAULT NULL,
	`Data` DATETIME NOT NULL,
	`Descrizione_veicolo` VARCHAR(100) NULL DEFAULT NULL,
	`Tipo_intervento` INT(11) NOT NULL,
	`Tipo_impianto` INT(11) NULL DEFAULT NULL,
	`Ragione_sociale` VARCHAR(100) NOT NULL,
	`Tipo_modello_impianto` VARCHAR(100) NULL DEFAULT NULL,
	`Stato_impianto` VARCHAR(100) NULL DEFAULT NULL,
	`Test_check_1` BIT(1) NOT NULL,
	`Test_check_2` BIT(1) NOT NULL,
	`Test_check_3` BIT(1) NOT NULL,
	`Test_check_4` BIT(1) NOT NULL,
	`Test_check_5` BIT(1) NOT NULL,
	`Test_check_6` BIT(1) NOT NULL,
	`Test_check_7` BIT(1) NOT NULL,
	`Test_check_8` BIT(1) NOT NULL,
	`Test_check_9` BIT(1) NOT NULL,
	`Test_check_10` BIT(1) NOT NULL,
	`Test_check_11` BIT(1) NOT NULL,
	`Test_check_12` BIT(1) NOT NULL,
	`Test_check_13` BIT(1) NOT NULL,
	`Test_check_14` BIT(1) NOT NULL,
	`Test_check_15` BIT(1) NOT NULL,
	`Test_check_16` BIT(1) NOT NULL,
	`Test_check_17` BIT(1) NOT NULL,
	`Test_check_18` BIT(1) NOT NULL,
	`Test_check_19` BIT(1) NOT NULL,
	`Test_check_20` BIT(1) NOT NULL,
	`Test_check_21` BIT(1) NOT NULL,
	`Test_check_22` BIT(1) NOT NULL,
	`Test_check_23` BIT(1) NOT NULL,
	`Test_check_24` BIT(1) NOT NULL,
	`Test_check_25` BIT(1) NOT NULL,
	`Test_check_26` BIT(1) NOT NULL,
	`Test_check_27` BIT(1) NOT NULL,
	`Test_check_28` BIT(1) NOT NULL,
	`Test_check_29` BIT(1) NOT NULL,
	`Test_check_30` BIT(1) NOT NULL,
	`Test_check_31` BIT(1) NOT NULL,
	`Test_check_32` BIT(1) NOT NULL,
	`Test_check_33` BIT(1) NOT NULL,
	`Test_check_34` BIT(1) NOT NULL,
	`Test_check_35` BIT(1) NOT NULL,
	`Test_check_36` BIT(1) NOT NULL,
	`Test_check_37` BIT(1) NOT NULL,
	`Test_check_38` BIT(1) NOT NULL,
	`Test_check_39` BIT(1) NOT NULL,
	`Test_check_40` BIT(1) NOT NULL,
	`Test_check_41` BIT(1) NOT NULL,
	`Test_check_42` BIT(1) NOT NULL,
	`Test_check_43` BIT(1) NOT NULL,
	`Test_check_44` BIT(1) NOT NULL,
	`Test_check_45` BIT(1) NOT NULL,
	`Test_check_46_1` BIT(1) NOT NULL,
	`Test_check_47_1` BIT(1) NOT NULL,
	`Test_check_48_1` BIT(1) NOT NULL,
	`Test_check_46_2` BIT(1) NOT NULL,
	`Test_check_47_2` BIT(1) NOT NULL,
	`Test_check_48_2` BIT(1) NOT NULL,
	`Test_check_46_3` BIT(1) NOT NULL,
	`Test_check_47_3` BIT(1) NOT NULL,
	`Test_check_48_3` BIT(1) NOT NULL,
	`Test_quantita_1` DECIMAL(11,2) NOT NULL,
	`Test_quantita_2` DECIMAL(11,2) NOT NULL,
	`Test_quantita_3` DECIMAL(11,2) NOT NULL,
	`Test_quantita_4` DECIMAL(11,2) NOT NULL,
	`Test_quantita_5` DECIMAL(11,2) NOT NULL,
	`Test_quantita_6` DECIMAL(11,2) NOT NULL,
	`Test_quantita_7` DECIMAL(11,2) NOT NULL,
	`Test_quantita_8` DECIMAL(11,2) NOT NULL,
	`Test_quantita_9` DECIMAL(11,2) NOT NULL,
	`Test_quantita_10` DECIMAL(11,2) NOT NULL,
	`Test_quantita_11` DECIMAL(11,2) NOT NULL,
	`Test_quantita_12` DECIMAL(11,2) NOT NULL,
	`Test_quantita_13` DECIMAL(11,2) NOT NULL,
	`Test_quantita_14` DECIMAL(11,2) NOT NULL,
	`Test_quantita_15` DECIMAL(11,2) NOT NULL,
	`Test_quantita_16` DECIMAL(11,2) NOT NULL,
	`Test_quantita_17` DECIMAL(11,2) NOT NULL,
	`Test_quantita_18` DECIMAL(11,2) NOT NULL,
	`Test_quantita_19` DECIMAL(11,2) NOT NULL,
	`Test_quantita_20` DECIMAL(11,2) NOT NULL,
	`Test_quantita_21` DECIMAL(11,2) NOT NULL,
	`Test_quantita_22` DECIMAL(11,2) NOT NULL,
	`Test_quantita_23` DECIMAL(11,2) NOT NULL,
	`Test_quantita_24` DECIMAL(11,2) NOT NULL,
	`Test_quantita_25` DECIMAL(11,2) NOT NULL,
	`Test_quantita_26` DECIMAL(11,2) NOT NULL,
	`Test_quantita_27` DECIMAL(11,2) NOT NULL,
	`Test_quantita_28` DECIMAL(11,2) NOT NULL,
	`Test_quantita_29` DECIMAL(11,2) NOT NULL,
	`Test_quantita_30` DECIMAL(11,2) NOT NULL,
	`Test_quantita_31` DECIMAL(11,2) NOT NULL,
	`Test_quantita_32` DECIMAL(11,2) NOT NULL,
	`Test_quantita_33` DECIMAL(11,2) NOT NULL,
	`Test_quantita_34` DECIMAL(11,2) NOT NULL,
	`Test_quantita_35` DECIMAL(11,2) NOT NULL,
	`Test_quantita_36` DECIMAL(11,2) NOT NULL,
	`Test_quantita_37` DECIMAL(11,2) NOT NULL,
	`Test_quantita_38` DECIMAL(11,2) NOT NULL,
	`Test_quantita_39` DECIMAL(11,2) NOT NULL,
	`Test_quantita_40` DECIMAL(11,2) NOT NULL,
	`Test_quantita_41` DECIMAL(11,2) NOT NULL,
	`Test_quantita_42` DECIMAL(11,2) NOT NULL,
	`Test_quantita_43` DECIMAL(11,2) NOT NULL,
	`Test_quantita_44` DECIMAL(11,2) NOT NULL,
	`Test_quantita_45` DECIMAL(11,2) NOT NULL,
	`Test_quantita_46_1` DECIMAL(11,2) NOT NULL,
	`Test_quantita_47_1` DECIMAL(11,2) NOT NULL,
	`Test_quantita_48_1` DECIMAL(11,2) NOT NULL,
	`Test_quantita_46_2` DECIMAL(11,2) NOT NULL,
	`Test_quantita_47_2` DECIMAL(11,2) NOT NULL,
	`Test_quantita_48_2` DECIMAL(11,2) NOT NULL,
	`Test_quantita_46_3` DECIMAL(11,2) NOT NULL,
	`Test_quantita_47_3` DECIMAL(11,2) NOT NULL,
	`Test_quantita_48_3` DECIMAL(11,2) NOT NULL,
	`Note` TEXT NULL,
	`Data_intervento` DATE NULL DEFAULT NULL,
	`Ora_inizio_intervento_1` TIME NULL DEFAULT NULL,
	`Ora_fine_intervento_1` TIME NULL DEFAULT NULL,
	`Ora_inizio_intervento_2` TIME NULL DEFAULT NULL,
	`Ora_fine_intervento_2` TIME NULL DEFAULT NULL,
	`Ore_intervento` VARCHAR(30) NULL DEFAULT NULL,
	`Ore_Viaggio` DECIMAL(11,2) NULL DEFAULT NULL,
	`Ore_totali` DECIMAL(11,2) NULL DEFAULT NULL,
	`Prezzo_ora` DECIMAL(11,2) NULL DEFAULT NULL,
	`Note_viaggio` VARCHAR(255) NULL DEFAULT NULL,
	`Numero_viaggi` TINYINT(4) NOT NULL,
	`Km_percorsi` TINYINT(4) NOT NULL,
	`Km_complessivi` TINYINT(4) NOT NULL,
	`Prezzo_km` DECIMAL(11,2) NOT NULL,
	`Totale_prezzo_viaggio` DECIMAL(11,2) NOT NULL,
	`Totale_prezzo_orario` DECIMAL(11,2) NOT NULL,
	`Totale_prezzo_materiale` DECIMAL(11,2) NOT NULL,
	`Imponibile` DECIMAL(11,2) NOT NULL,
	`Iva` DECIMAL(11,2) NOT NULL,
	`Totale_prezzo` DECIMAL(11,2) NOT NULL,
	`Inviato` BIT(1) NULL DEFAULT b'0',
	`Processato` BIT(1) NULL DEFAULT b'0',
	`Utente_inserimento` SMALLINT(6) NOT NULL,
	`Operaio_inserimento` SMALLINT(6) NOT NULL,
	`Timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`),
	UNIQUE INDEX `Id_rapporto_Anno` (`Id_rapporto`, `Anno`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
