ALTER TABLE `lista_prelievo`
	ADD COLUMN `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `id_utente`;
ALTER TABLE `lista_prelievo`
	CHANGE COLUMN `rientro` `rientro` BIT NULL DEFAULT NULL AFTER `Id_operaio`;
