CREATE TABLE `Evento` (
	`Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Oggetto` VARCHAR(50) NOT NULL,
	`Descrizione` TEXT NOT NULL,
	`Attivo` BIT NOT NULL,
	`Id_riferimento` SMALLINT NULL,
	`Id_tipo_evento` TINYINT UNSIGNED NOT NULL,
	`Data_ins` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`Data_mod` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`Utente_ins` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`Utente_mod` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
